version: '2'
services:
  cache:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: ayou
      MYSQL_DATABASE: ayou
      MYSQL_USER: ayou
      MYSQL_PASSWORD: ayou
    ports:
      - '3306:3306'

  portal:
    build: .
    volumes:
      - .:/lambda
    command: python3 /lambda/src/main_portal.py
    links:
      - cache
      - db
    depends_on:
      - cache
      - db

  citylist:
    build: .
    volumes:
      - .:/lambda
    command: python3 /lambda/src/main_citylist.py
    links:
      - cache
      - db
    depends_on:
      - cache
      - db

  poilist:
    build: .
    volumes:
      - .:/lambda
    command: python3 /lambda/src/main_poilist.py
    links:
      - cache
      - db
    depends_on:
      - cache
      - db

  poidetail:
    build: .
    volumes:
      - .:/lambda
    command: python3 /lambda/src/main_poidetail.py
    links:
      - cache
      - db
    depends_on:
      - cache
      - db

volumes:
  dbdata:

